<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var Magento\Framework\Escaper $escaper
 */
?>
<div class="js-todo" data-bind="scope: 'todo'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        ".js-todo": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "todo": {
                        "component": "uiCollection",
                        "children": {
                            "form": {
                                "component": "Inevix_Todo/js/view/form"
                            },
                            "list": {
                                "component": "Inevix_Todo/js/view/list"
                            }
                        }
                    }
                }
            }
        }
    }
</script>
